title: Guangxin Yang
logo: /assets/img/Alan.png
description: Alan's Web Page
show_downloads: true
google_analytics: UA-233077999-1

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
